{% set name = "opentelemetry-instrumentation-mistralai" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: b632f10893db7382fb3fa7b355d10d76ebe87bfa6e5768344f1e701c050e7961

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0
  run_constrained:
    - mistralai >=1.0.0,<2.0.0

# Need to be authorized to run tests:
# E   mistralai.models.sdkerror.SDKError: API error occurred: Status 401
# E   {"detail":"Unauthorized"}
test:
  imports:
    - opentelemetry.instrumentation.mistralai
  commands:
    - pip check
  requires:
    - pip
    - mistralai >=1.0.0,<2.0.0

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Mistral AI instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing calls to any of mistralai's endpoints sent with the official Mistral AI library.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - reachable_url
